version: '3.8'

services:
  btt-auto-manager:
    # Development overrides
    environment:
      - DEBUG=true
      - LOG_LEVEL=DEBUG
    volumes:
      - ./getsql.log:/app/getsql.log  # Mount log file for debugging
    # Enable interactive mode for debugging
    stdin_open: true
    tty: true 