name: Docker Build and Test

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: btt-auto-manager:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Test Docker image
      run: |
        # Start container
        docker run -d --name test-btt -p 5680:5680 btt-auto-manager:latest
        
        # Wait for startup
        sleep 30
        
        # Test health endpoint
        curl -f http://localhost:5680/healthz || exit 1
        
        # Test status endpoint
        curl -f http://localhost:5680/status || exit 1
        
        # Cleanup
        docker stop test-btt
        docker rm test-btt
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: docker-image
        path: |
          Dockerfile
          docker-compose.yml
          requirements.txt
        retention-days: 30 